;METADATA=(Diff=true, UseCommands=true)
[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagList=(Tag="Damage.Trait.Knockback",DevComment="")
+GameplayTagList=(Tag="Data.Damage",DevComment="")
+GameplayTagList=(Tag="Data.Heal",DevComment="")
+GameplayTagList=(Tag="Data.Knockback.Magnitude",DevComment="")
+GameplayTagList=(Tag="Event.Abilities.Changed",DevComment="")
+GameplayTagList=(Tag="Event.ActivateAbility.Dash",DevComment="")
+GameplayTagList=(Tag="Event.ActivateAbility.Fireball",DevComment="")
+GameplayTagList=(Tag="Event.ActivateAbility.Stomp",DevComment="")
+GameplayTagList=(Tag="Event.Combat.Death",DevComment="")
+GameplayTagList=(Tag="Event.Hit.Knockback",DevComment="")
+GameplayTagList=(Tag="Event.Hit.Stomp",DevComment="")
+GameplayTagList=(Tag="Event.Score.Changed",DevComment="")
+GameplayTagList=(Tag="Event.Spell.Summon",DevComment="")
+GameplayTagList=(Tag="Event.UI.CastBar.Start",DevComment="")
+GameplayTagList=(Tag="GameplayAbility.Death",DevComment="")
+GameplayTagList=(Tag="GameplayAbility.Movement.Dash",DevComment="")
+GameplayTagList=(Tag="GameplayAbility.Movement.Knockback",DevComment="")
+GameplayTagList=(Tag="GameplayAbility.Movement.Stomp",DevComment="")
+GameplayTagList=(Tag="GameplayAbility.Spell.Fireball",DevComment="")
+GameplayTagList=(Tag="GameplayAbility.State.Cooldown.Fireball",DevComment="")
+GameplayTagList=(Tag="GameplayAbility.State.Cooldown.Knockback",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Explosion",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Projectile.Fireball",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Projectile.Fireball.Explosion",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Projectile.Fireball.Trail",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Stomp.Impact",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Stomp.Travel",DevComment="")
+GameplayTagList=(Tag="State.Casting",DevComment="")
+GameplayTagList=(Tag="State.Dead",DevComment="")
+GameplayTagList=(Tag="Status.Health.Regen",DevComment="")
+GameplayTagList=(Tag="Status.Mana.Regen",DevComment="")
+GameplayTagList=(Tag="Type.Bouncy",DevComment="")

